name: 'Publish Docker'
author: 'zb'
branding:
  icon: 'anchor'
  color: 'blue'
description: 'Uses the git branch as the docker tag and pushes the container'
inputs:
  name:
    description: 'The name of the image you would like to push'
    required: true
  username:
    description: 'The login username for the registry'
    required: true
  password:
    description: 'The login password for the registry'
    required: true
  registry:
    description: 'Use registry for pushing to a custom registry'
    required: false
  tags:
    description: 'Use tags when you want to bring your own tags (separated by comma)'
    required: false
    default: 'latest'
  no_push:
    description: 'Set no_push to true if you want to prevent the action from pushing to a registry (default: false)'
    required: false
  project_name:
    description: 'Set publish project name'
    required: true
  aws_credentials:
    description: 'aws credentials'
    required: true
  aws_config:
    description: 'aws config'
    required: true  
  kube_config:
    description: 'kube config'
    required: true 
outputs:
  tag:
    description: 'Is the tag, which was pushed'
  snapshot-tag:
    description: 'Is the tag that is generated by the snapshot-option and pushed'
  digest:
    description: 'Is the digest of the image, which was pushed'
runs:
  using: 'docker'
  image: 'Dockerfile'
